#deployment aplicação temperatura

apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
      - name: conversaotemperatura
        image: eudespaz/conversao-temperatura:1.0
---

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001        
  type: NodePort

               
